Andrew onboarding refactor
BrickLabsInc/frontend pull request #10
Opened 2020-08-27 23:36 UTC by ahamacher

This refactor removes Maxwell from the onboarding process as well as changes the way the onboarding components work.

All onboarding questions now require a react component to handle the question. This allows us to have any number of fields on an onboarding tile.

Fix the dashboard display as the information from our backend was being received at a different time than required with the refactor changes.

2020-09-17 15:42 UTC, JibbyAni requested changes
Left a few comments! Once changes are made tag me for a re-review and I'll take another look over

2020-09-17 20:47 UTC, ahamacher commented on src/components/header/header.js
> +    window.location.href = "http://localhost:3000/"
This is being addressed in a future PR. It no longer uses an exact route and instead uses the relative route through the react-router.

2020-09-17 20:52 UTC, ahamacher commented on src/utils/validate.js
> +export const passwordValidation = (passwords) => {
Totally agree on a more secure password, I actually think we should force more than just 1 number and 1 character, could we make it so it is 1 number, 1 symbol and at least 1 uppercase and lowercase letter? 

Could we leave this as it is now as it makes it easier for testing to have a simple password when I am making and entering in 10-20 accounts per day. I was thinking an updated verification could be included in the forgot password Trello tile.

2020-09-22 01:12 UTC, ahamacher commented on src/components/confirmation/confirmation.js
> +// data flow diagram for bloom
these were missed in deletion of my personal notes on how i wanted to construct the component. deleted.

2020-09-22 01:16 UTC, ahamacher commented on src/utils/profileApiUtil.js
>  export const newProfile = payload => {
This api route is never used as I use the one in userApiUtils to create a new customer. Deleted this and all references / imports as they were never called in the components.

2020-09-22 01:21 UTC, ahamacher commented on src/utils/profileApiUtil.js
> +};
Get profile gets all of a profiles attributes, we dont need to specify the ID as the id is encrypted into the session cookie provided by firebase and is decoded on our backend. 

updated all sendProfiles with newProfile

2020-09-22 01:22 UTC, ahamacher commented on src/components/dashboard/dashTiles/addressModule.js
> +    let address = "Test Address Delete Before Push";
deleted.

2020-09-22 01:23 UTC, ahamacher commented on src/components/dashboard/dashTiles/valuationModule.js
> +    let valuation = "Test valuation Delete Before Push";
deleted.

2020-09-22 01:25 UTC, ahamacher commented on src/components/dashboard/dashboard.js
> +    console.log("hit the dashboard use effect");
This was just testing to see if my component was loading correctly, and if the useEffect was being properly called on a component load. It has no further purposed and has been deleted.

2020-09-22 01:26 UTC, ahamacher commented on src/utils/verifyUtil.js
> +// TODO: implement resending of codes
deleted.

2020-09-22 01:26 UTC, ahamacher commented on src/utils/validate.js
> +  if (social.length !== 4) {
at the time of this PR we were still only seeking the last 4 of a SSN, the change for a full SSN is in a future PR.

2020-09-22 01:29 UTC, ahamacher commented on src/utils/assetProfileUtil.js
> +export const newAssetProfile = () => {
Added in comments but here as well. An asset profile is all the information that pertains to a specific Asset or in other terms a customer's property.

2020-09-22 01:32 UTC, ahamacher commented on src/components/splash/test.js
> +  const getPersonInfo = () => {
deleted, but left the component. I use this component when i am building out new features to test the routes from the "splash" page. It is something that will be removed once we have an actual splash page to show, for now I have deleted the references to maxwell though.

2020-09-22 01:34 UTC, ahamacher commented on src/components/session/verify.js
> +import React, { useState } from 'react';
This whole component is replaced in a future PR (repurposed for bloom KBA). Replacing it here will make more work in fixing all the conflicts in the future.

2020-09-22 01:34 UTC, ahamacher commented on src/constants/constants.js
> +        maxwellOTP: "Please enter the One Time Passcode that was sent to the phone-number provided",
deleted.

2020-09-22 01:34 UTC, ahamacher commented on src/components/dashboard/dashTiles/valuationModule.js
> +    // useEffect(() => {
deleted.

2020-09-22 05:14 UTC, JibbyAni approved these changes
Looks good!

2020-09-22 05:14 UTC, merged